import { CategoryRecieptPDFDc } from './category-master-dc';

export class BillRecieptDc {
	public BillRecieptId: number;
	public UserId: number;
	public CategoryRecieptId: number;
	public CurrencyId: number;
	public FontId: number;
	public FontStyle: string;
	public RecieptDate: string;
	public Business: string;
	public Address: string;
	public CityState: string;
	public MobileNo: string;
	public RecieptLogo: any;
	public CreatedDate: Date;
	public Name: string;
	public CategoryName: string;
	public BillRecieptDynamicHtml: string;
	public Currency: string;
	public RecieptNo: string;
	public PaymentType: string;
	// General Fields
	public Auth: string;
	public Trans: string;
	public Mcc: string;
	public ApprCode: string;
	// Gas Reciept Fields
	public WebSiteName: string;
	public DocNo: string;
	public GSTNo: string;
	public BillNo: string;
	public AtndId: string;
	public FPId: string;
	public Pump: string;
	public NozlNo: string;
	public Fuel: string;
	public Density: string;
	public TinNo: string;
	public TRXId: string;
	public AccountNo: string;
	public PompaSalans: string;
	public NomarNota: string;
	public JenisBBM: string;
	public StationNo: string;
	// Grocery Fields
	public HelplineNo: string;
	public LandlineNo: string;
	public CINNo: string;
	public STNo: string;
	public OPNo: string;
	public TENo: string;
	public TCNo: string;
	public REFNo: string;
	public Validation: string;
	public PaymentService: string;
	public PayAmount: number;
	public Lane: string;
	public Clerk: string;
	public Cashier: string;
	public MRCH: string;
	public EPSSequence: string;
	public NetworkId: string;
	public TerminalId: string;
	// Parking Fields
	public SpaceNo: string;
	public TicketNo: string;
	public SNNo: string;
	public Lot_Location: string;
	public PayedAt: string;
	public EntryDate: string;
	public ExitDate: string;
	public MachName: string;
	public VehicleNo: string;
	public VehicleType: string;

	//Pharmacy Fields
	public RegNo: string;
	public TRNNo: string;
	public CSHRNo: string;
	public STRNo: string;
	public HelpedBy: string;
	public AID: string;
	public Signature: string;
	public CVM: string;
	public StoreNo: string;
	public PharmacyNo: string;
	//Restaurant Fields
	public OrderNo: string;
	public OrderDate: string;
	public DeliveryDate: string;
	public Host: string;
	public FaxNo: string;
	public BillTo: string;
	public BillToEmailId: string;
	public ShipTo: string;
	public CustomerNo: string;
	public CustomerPONo: string;
	public CardEntry: string;
	public TransType: string;
	public CheckNo: string;
	public CheckId: string;
	public Tip: string;
	//Taxi Fields
	public TaxiDate: string;
	public PickupTime: string;
	public DropTime: string;
	public PickupAddress: string;
	public DropAddress: string;
	public TaxiKM: string;
	public CarName: string;
	public Miles: string;
	public TaxiWTTime: string;
	public BaseFare: number;
	public DistanceFare: number;
	public TimeFare: number;
	public SubCharges: number;
	public SafeRideFee: number;
	public TaxiCallNo: string;
	public ProfileImage: string;
	public LiftLineDiscountPrice: number;
	public PromotionalPricing: number;
	public RideBy: string;
	public LicensePlate: string;
	public Rating: number;
	//Toll Fields
	public TollPlaza: string;
	public Operator: string;
	public Section: string;
	public VehicleStanderedWeight: string;
	public VehicleActualWeight: string;
	public OverloadedVehicleFee: number;
	public Shift: string;
	public Journey: string;
	public TCId: string;
	public BarCode: string;
	public CSH: string;
	//Phone & Internet Fields
	public RelationShipNo: string;
	public BillDate: string;
	public DueDate: string;
	public LandMark: string;
	public BillPeriod: string;
	public BillPayDate: string;
	public CreditLimit: number;
	public SecurityDeposit: number;
	public PreviousBalance: number;
	public Payments: number;
	public Adjustments: number;
	public LatePaymentFee: number;
	public MonthlyRentals: number;
	public UsageCharges: number;
	public OneTimeCharges: number;
	public Taxes: number;
	public ServiceTaxRegNo: string;
	public FixedlineNo: string;
	public BroadbandId: string;
	public AlternateMobileNo: string;
	public ShipToStateCode: string;
	public BillGenerateBy: string;
	public SoldBy: string;
	public SyNo: string;
	public PANNo: string;
	public InvoiceDetails: string;
	public AadharNo: string;
	public MemberShip: string;
	public UsageP_ISD_IRCalling: number;
	public UsageDataCharges: number;
	public UsageSMSCharges: number;
	public UsageVASCharges: number;
	public CurruntMonthDiscount: number;
	public BillDiscountWithTax: number;
	public FormDataImages: any;
	// multiple data
	public SubscriptionPlanId: number;
	public BillRecieptItemInfoDc: Array<BillRecieptItemInfoDc>;
	public BillRecieptTaxInfoDc: Array<BillRecieptTaxInfoDc>;
	public CategoryRecieptPDFDc: CategoryRecieptPDFDc;
}

export class BillRecieptSearchDc {
	public BillRecieptId: number;
	public UserId: number;
	public CategoryId: number;
	public Business: string;
	public RecieptNo: string;
	public RecieptFromDate: string;
	public RecieptToDate: string;
}

export class BillRecieptItemInfoDc {
	public BillRecieptItemId: number;
	public BillRecieptId: number;
	public ItemNo: string;
	public ItemName: string;
	public Quantity: number;
	public Price: number;
	public Description: string;
	public Type: string;
	public Mfrs: string;
	public BatchNo: string;
	public Expiry: string;
	public UOM: string; 
	public CreatedDate: Date;
}

export class BillRecieptTaxInfoDc {
	public BillRecieptTaxId: number;
	public BillRecieptId: number;
	public TaxId: number;
	public TaxInPercentage: number;
	public Tax: string;
}